// <auto-generated />
using System;
using Masroo3k.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Masroo3k.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("_localizer["auto.20251108003019_InitialCreateSQLServer.Designer.f31f7e3b"]")]
    partial class InitialCreateSQLServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Masroo3k.Api.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.fa7153f7"]");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("_localizer["auto.20251108003019_InitialCreateSQLServer.004bf6c9"]")
                        .IsRequired()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.47b2e8f4"]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.dca44442"]");

                    b.Property<string>("_localizer["templateBuilder.description"]")
                        .IsRequired()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.d78cbc7b"]");

                    b.Property<string>("_localizer["auto.20251108003019_InitialCreateSQLServer.Designer.3ec365dd"]")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.d78cbc7b"]");

                    b.Property<int?>("EntityId")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.fa7153f7"]");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.d78cbc7b"]");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.d78cbc7b"]");

                    b.Property<string>("_localizer["auto.20251108003019_InitialCreateSQLServer.007cc954"]")
                        .IsRequired()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.47b2e8f4"]");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.d78cbc7b"]");

                    b.Property<int?>("UserId")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.fa7153f7"]");

                    b.HasKey("Id");

                    b.HasIndex("_localizer["auto.20251108003019_InitialCreateSQLServer.004bf6c9"]");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("_localizer["auto.20251108003019_InitialCreateSQLServer.007cc954"]");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.Analysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.fa7153f7"]");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("_localizer["auto.20251108003019_InitialCreateSQLServer.Designer.f15c1cae"]")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.d78cbc7b"]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.dca44442"]");

                    b.Property<string>("ExecutiveSummary")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.d78cbc7b"]");

                    b.Property<decimal>("ExpectedROI")
                        .HasColumnType("_localizer["auto.AppDbContext.e246d6fa"]");

                    b.Property<decimal>("_localizer["report.investment"]")
                        .HasColumnType("_localizer["auto.AppDbContext.e246d6fa"]");

                    b.Property<string>("KeyFindings")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.d78cbc7b"]");

                    b.Property<int>("OwnerId")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.fa7153f7"]");

                    b.Property<string>("_localizer["report.recommendations"]")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.d78cbc7b"]");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.d78cbc7b"]");

                    b.Property<int>("_localizer["analyses.score"]")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.fa7153f7"]");

                    b.Property<int>("SuccessPercent")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.fa7153f7"]");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.fa7153f7"]");

                    b.Property<string>("_localizer["auto.20251108003019_InitialCreateSQLServer.Designer.b78a3223"]")
                        .IsRequired()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.d78cbc7b"]");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TemplateId");

                    b.ToTable("_localizer["admin.analyses"]");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.fa7153f7"]");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionUrl")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.d78cbc7b"]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.dca44442"]");

                    b.Property<bool>("IsRead")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.f67169df"]");

                    b.Property<string>("_localizer["auto.20251108003019_InitialCreateSQLServer.Designer.4c2a8fe7"]")
                        .IsRequired()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.d78cbc7b"]");

                    b.Property<string>("_localizer["auto.20251108003019_InitialCreateSQLServer.Designer.b78a3223"]")
                        .IsRequired()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.d78cbc7b"]");

                    b.Property<string>("_localizer["auto.20251108003019_InitialCreateSQLServer.Designer.a1fa2777"]")
                        .IsRequired()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.d78cbc7b"]");

                    b.Property<int>("UserId")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.fa7153f7"]");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRead");

                    b.HasIndex("UserId");

                    b.ToTable("_localizer["notifications.title"]");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.fa7153f7"]");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("_localizer["templateBuilder.categoryAria"]")
                        .IsRequired()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.d78cbc7b"]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.dca44442"]");

                    b.Property<string>("_localizer["templateBuilder.description"]")
                        .HasMaxLength(280)
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.80e986b3"]");

                    b.Property<int>("_localizer["templates.duration"]")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.fa7153f7"]");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.f67169df"]");

                    b.Property<string>("_localizer["auto.20251108003019_InitialCreateSQLServer.Designer.49ee3087"]")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.02bd0ece"]");

                    b.HasKey("Id");

                    b.ToTable("_localizer["admin.templates"]");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.TemplateField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.fa7153f7"]");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.dca44442"]");

                    b.Property<string>("FieldOptions")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.d78cbc7b"]");

                    b.Property<int>("FieldOrder")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.fa7153f7"]");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.d78cbc7b"]");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.f67169df"]");

                    b.Property<string>("_localizer["fieldBuilder.labelPlaceholder"]")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.02bd0ece"]");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.fa7153f7"]");

                    b.Property<int?>("MinLength")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.fa7153f7"]");

                    b.Property<bool>("MustBeBetween0And100")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.f67169df"]");

                    b.Property<bool>("MustBePositive")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.f67169df"]");

                    b.Property<bool>("MustBeValidUrl")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.f67169df"]");

                    b.Property<string>("_localizer["auto.20251108003019_InitialCreateSQLServer.Designer.ed0a5a06"]")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.722bbc65"]");

                    b.Property<int>("StageNumber")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.fa7153f7"]");

                    b.Property<int>("TemplateId")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.fa7153f7"]");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "StageNumber", "FieldOrder");

                    b.ToTable("TemplateFields");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.fa7153f7"]");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.dca44442"]");

                    b.Property<string>("_localizer["auto.20251108003019_InitialCreateSQLServer.ce8ae9da"]")
                        .IsRequired()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.47b2e8f4"]");

                    b.Property<string>("_localizer["auto.20251108003019_InitialCreateSQLServer.Designer.49ee3087"]")
                        .IsRequired()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.d78cbc7b"]");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.d78cbc7b"]");

                    b.Property<string>("_localizer["profile.role"]")
                        .IsRequired()
                        .HasColumnType("_localizer["auto.20251108003019_InitialCreateSQLServer.d78cbc7b"]");

                    b.HasKey("Id");

                    b.HasIndex("_localizer["auto.20251108003019_InitialCreateSQLServer.ce8ae9da"]")
                        .IsUnique();

                    b.ToTable("_localizer["admin.users"]");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.ActivityLog", b =>
                {
                    b.HasOne("Masroo3k.Api.Models.User", "_localizer["profile.user"]")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("_localizer["profile.user"]");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.Analysis", b =>
                {
                    b.HasOne("Masroo3k.Api.Models.User", "_localizer["auto.20251108003019_InitialCreateSQLServer.Designer.b6f4a2ec"]")
                        .WithMany("_localizer["admin.analyses"]")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Masroo3k.Api.Models.Template", "_localizer["auto.20251108003019_InitialCreateSQLServer.Designer.278c491b"]")
                        .WithMany("_localizer["admin.analyses"]")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("_localizer["auto.20251108003019_InitialCreateSQLServer.Designer.b6f4a2ec"]");

                    b.Navigation("_localizer["auto.20251108003019_InitialCreateSQLServer.Designer.278c491b"]");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.Notification", b =>
                {
                    b.HasOne("Masroo3k.Api.Models.User", "_localizer["profile.user"]")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_localizer["profile.user"]");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.TemplateField", b =>
                {
                    b.HasOne("Masroo3k.Api.Models.Template", "_localizer["auto.20251108003019_InitialCreateSQLServer.Designer.278c491b"]")
                        .WithMany("Fields")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_localizer["auto.20251108003019_InitialCreateSQLServer.Designer.278c491b"]");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.Template", b =>
                {
                    b.Navigation("_localizer["admin.analyses"]");

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.User", b =>
                {
                    b.Navigation("_localizer["admin.analyses"]");
                });
#pragma warning restore 612, 618
        }
    }
}
